
services:

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      VITE_AUTH_API: http://localhost:5001
      VITE_PAYMENT_API: http://localhost:5002
      VITE_BACKEND_API: http://localhost:5050
      VITE_GOOGLE_CLIENT_ID: 626542173826-rfe88551gp792f882c299s5mbn19hos3.apps.googleusercontent.com
      VITE_RECAPTCHA_SITE_KEY: 6LfDojcsAAAAAEAwzAg1EczIejEpilaUUWGf1I1P
    depends_on:
      - auth-service
      - payment-service
      - backend-service

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongodb:27017/virtual_exhibition
      SESSION_SECRET: vg_s3ss10n_k3y_Pr3mBhuvan_2006_Secure!XYZ
      GOOGLE_CLIENT_ID: 626542173826-rfe88551gp792f882c299s5mbn19hos3.apps.googleusercontent.com
      RECAPTCHA_SECRET_KEY: 6LfDojcsAAAAAJ3Y3HV1kl8AHYxXUxAJeA09uAN7
      EMAIL_USER: dbpb1999@gmail.com
      EMAIL_PASS: thfnqlhyyozkdxuj
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      MONGO_URI: mongodb://mongodb:27017/virtual_exhibition
      SESSION_SECRET: vg_s3ss10n_k3y_Pr3mBhuvan_2006_Secure!XYZ
      RAZORPAY_KEY_ID: rzp_test_RskyYl6VJe3ytS
      RAZORPAY_KEY_SECRET: BIsjVgg0qh7OXleVs1TFWguw
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongodb

  backend-service:
    build: ./backend-service
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      MONGO_URI: mongodb://mongodb:27017/virtual_exhibition
      SESSION_SECRET: vg_s3ss10n_k3y_Pr3mBhuvan_2006_Secure!XYZ
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: